[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "devops_five"
version = "0.1.0"

dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic-settings",
    "httpx",
    "pytest"
]